version: '3.3'

services:
  api:
    build: 
      context: .
    image: easyquiz-graphql:latest
    container_name: easyquiz-graphql
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
  db:
    image: postgres:12
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PWD}
      - POSTGRES_USER=${DB_USER}
    ports:
      - "${DB_PORT}:5432"