name: build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npm run ts-lint
    - name: Build
      run: npm run build
    - name: Tests
      run: npm run test
      env:
        DB_IS_POSTGRES: ''
        DB_STORAGE: './__tests__/database.sqlite'
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: ./__tests__/coverage/lcov.info